---
abstract: 'API for the Postmark mail service for web applications.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Postmark
requires:
  Carp: 0
  Email::Valid: 0
  JSON::Any: 0
  LWP::UserAgent: 0
  Try::Tiny: 0
  perl: 5.010
resources:
  homepage: http://github.com/ido50/WWW-Postmark/tree
  repository: git://github.com/ido50/WWW-Postmark.git
version: 0.2
