---
abstract: 'API for the Postmark mail service for web applications.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Postmark
requires:
  Carp: 0
  Email::Valid: 0
  HTTP::Tiny: 0
  JSON::Any: 0
  Try::Tiny: 0
  feature: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: http://github.com/ido50/WWW-Postmark
  repository: http://github.com/ido50/WWW-Postmark
version: 0.3
