---
abstract: 'API for the Postmark mail service for web applications.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Postmark
recommends:
  JSON::XS: 2.3
requires:
  Carp: 0
  Email::Valid: 0
  HTTP::Tiny: 0
  JSON: 0
  feature: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/ido50/WWW-Postmark
  repository: https://github.com/ido50/WWW-Postmark.git
version: 0.5
